# Generated by Django 4.1.7 on 2023-03-09 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='last_service_date',
            new_name='last_battery_service_date',
        ),
        migrations.AddField(
            model_name='car',
            name='last_serviced_millage',
            field=models.IntegerField(blank=True, default=0, max_length=12),
            preserve_default=False,
        ),
    ]
