# Generated by Django 4.1.7 on 2023-03-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rename_last_service_date_car_last_battery_service_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='last_serviced_millage',
            field=models.IntegerField(blank=True, default=0, max_length=12),
        ),
    ]
