# Generated by Django 4.1.7 on 2023-03-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_allcarsneedingservicing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='current_millage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='last_serviced_millage',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='servicecriteria',
            name='due',
            field=models.IntegerField(),
        ),
    ]
